---
include:
  # Scanner mode (non-touch by default)
  - board: seeeduino_xiao_ble
    shield: prospector_scanner
    cmake-args: -DEXTRA_CONF_FILE=../../config/overrides.conf

  # Settings reset utility
  - board: seeeduino_xiao_ble
    shield: settings_reset